name: instagram
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # ui widgets
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1    
  cached_network_image: ^3.3.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dartz: ^0.10.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.1.0
  connectivity_plus: ^5.0.2
  get_it: ^7.6.4
  path_provider: ^2.1.1
  pretty_dio_logger: ^1.3.1
  photo_view: ^0.14.0
  image_picker: ^0.8.6
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  fluttertoast: ^8.2.4
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Italic.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 400
        - asset: assets/fonts/Roboto-BlackItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic

